export * from './FOCUS.jpeg'
export * from './He.jpeg'
export * from './Jesus.jpeg'
export * from './ghost.jpeg'
export * from './squid.jpeg'
export * from './tooth.jpeg'
export * from './zoot.jpeg'
export * from './ultimi.jpeg'